### ISSUE TITLE
Trying to use ModSurfer with GitLab CI

### ISSUE THREAD

**Issue by k33g** [dylibso/modsurfer#32]
👋  I'm trying to use ModSurfer with GitLab CI. I did several ways.

### Use the official image (distroless images are not usable with GitLab CI)

```yaml
1-analyze-go-plugin:
  stage: analyze-plugins
  allow_failure: true
  image: ghcr.io/dylibso/modsurfer:latest
  variables:
    WASM_MODULE: "hello-go.wasm" 
  artifacts:
    paths:
      - ${WASM_MODULE}    
  script: |
    ./cli/modesurfer validate -p ${WASM_MODULE} -c ${WASM_MODULE}.yaml
```

But it failed with `error: unrecognized subcommand 'sh'`

And it's probably because of the `distroless` image: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26501

### Create my image (but I'm doing my baby steps with docker)

So I try to build my image (adding a shell)

```Dockerfile
FROM rust:latest as builder

RUN update-ca-certificates
RUN git clone https://github.com/dylibso/modsurfer.git

WORKDIR /modsurfer
COPY . .

RUN cargo build --release

FROM busybox:1.36.0-uclibc as busybox

FROM gcr.io/distroless/cc

LABEL org.opencontainers.image.source=https://github.com/dylibso/modsurfer
LABEL org.opencontainers.image.description="Modsurfer CLI image, learn more at https://dev.dylib.so/docs/modsurfer/cli"
LABEL org.opencontainers.image.licenses=Apache-2.0

# Copy the static shell into base image.
COPY --from=busybox /bin/sh /bin/sh

WORKDIR /cli

COPY --from=builder /modsurfer/target/release/modsurfer ./
#ENTRYPOINT ["/cli/modsurfer"]
```

And I can run `docker run ${IMAGE_NAME} ./modsurfer --version` with success, but I need to digg more because, when I run the new CI Job, the CLI cannot "see" my file (I probably forget something with the docker file).

```yaml
2-analyze-go-plugin:
  stage: analyze-plugins
  allow_failure: true
  image: registry.gitlab.com/k33g_org/modsurfer-experiments/modsurfer-image/modsurfer-for-gitlab:0.0.0
  variables:
    WASM_MODULE: "hello-go.wasm" 
  artifacts:
    paths:
      - ${WASM_MODULE}    
  script: |
    ./cli/modesurfer validate -p ${WASM_MODULE} -c ${WASM_MODULE}.yaml
```

### Download the release file (dependency issue)

```yaml
3-analyze-go-plugin:
  stage: analyze-plugins
  allow_failure: true
  image: gitpod/workspace-full:latest
  artifacts:
    paths:
      - ${WASM_MODULE}
  variables:
    WASM_MODULE: "hello-go.wasm" 
  before_script:
    - curl -L https://github.com/dylibso/modsurfer/releases/download/v0.0.7/modsurfer-x86_64-unknown-linux-gnu.tar.gz > modsurfer-x86_64-unknown-linux-gnu.tar.gz
    - tar -C ./ -xzf modsurfer-x86_64-unknown-linux-gnu.tar.gz
  script: |
    ./modsurfer validate -p ${WASM_MODULE} -c ${WASM_MODULE}.yaml
```

When I try to execute `modsurfer` I get this message:

```bash
./modsurfer: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```

### Using `cargo run` (it works 🎉 but it's little bit long)

```yaml
4-analyze-go-plugin:
  stage: analyze-plugins
  image: gitpod/workspace-full:latest
  allow_failure: true
  artifacts:
    paths:
      - ${WASM_MODULE}
  variables:
    WASM_MODULE: "hello-go.wasm" 
  script: |
    git clone https://github.com/dylibso/modsurfer.git
    cd modsurfer/cli
    cargo run -- validate -p ../../${WASM_MODULE} -c ../../${WASM_MODULE}.yaml
``` 

If you have any idea about the dependency issue:

```bash
./modsurfer: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```
It will solve my problem
